[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
image = "0.25.6"
rand = "0.8.5"
indicatif = "0.17.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
